---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  user: deploy
  become: True
  gather_facts: True

  roles:
    - common
    - mailserver
    - webmail
    - blog
    - ircbouncer
    - xmpp
    - owncloud
    - vpn
    - tarsnap
    - news
    - git
    - readlater
    - mangaserver
    - monitoring  # Monitoring role should be last. See roles/monitoring/README.md
