- name: Download check-rbl
  get_url: >-
    url=https://raw.githubusercontent.com/lukecyca/check-rbl/479c1d5aa57543ba4c495ef06028fd9092ffdf43/check-rbl.pl
    dest=/opt/check-rbl.pl
    checksum=sha256:0968ea1991b500a2bb39b4aefb05c6bf42a62994774f2c46de5d426d5094508b

- name: Install nightly check-rbl cronjob
  cron: name="check-rbl" special_time=weekly job="perl /opt/check-rbl.pl -i {{ ansible_default_ipv4.address }}"
